# Generated by Django 3.2.4 on 2021-07-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=120, null=True)),
                ('empAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('empEmail', models.CharField(max_length=120, null=True)),
                ('Department', models.CharField(max_length=10, null=True)),
                ('empID', models.IntegerField()),
            ],
        ),
    ]
