# Generated by Django 3.2.4 on 2021-07-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0002_rename_empmodel_empdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='empAddress',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
