# Generated by Django 3.2.4 on 2021-07-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0006_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdata',
            old_name='Department',
            new_name='Team',
        ),
    ]
