# Generated by Django 3.2.4 on 2021-07-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0007_rename_department_empdata_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Team',
        ),
    ]
