# Generated by Django 3.2.4 on 2021-07-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0008_rename_department_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='empdata',
            old_name='Team',
            new_name='Department',
        ),
    ]
