# Generated by Django 3.2.4 on 2021-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0009_auto_20210707_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdata',
            name='empPhone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
