# Generated by Django 3.2.4 on 2021-07-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0010_empdata_empphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdata',
            name='empGender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='Male', max_length=20),
        ),
    ]
