# Generated by Django 3.2.4 on 2021-07-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0011_empdata_empgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='empGender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=20),
        ),
    ]
