# Generated by Django 3.2.4 on 2021-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0012_alter_empdata_empgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='empID',
            field=models.IntegerField(blank=True),
        ),
    ]
