# Generated by Django 3.2.4 on 2021-07-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0014_alter_empdata_empid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdata',
            old_name='empAddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='empdata',
            old_name='empEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='empdata',
            old_name='empGender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='empdata',
            old_name='empName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='empdata',
            old_name='empPhone',
            new_name='Phone',
        ),
    ]
