# Generated by Django 3.2.4 on 2021-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0015_auto_20210708_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdata',
            name='apporovedStatus',
            field=models.BooleanField(default=False),
        ),
    ]
