# Generated by Django 3.2.4 on 2021-07-08 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0017_rename_apporovedstatus_empdata_apporoved_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.CharField(max_length=12)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.empdata')),
            ],
        ),
    ]
