# Generated by Django 3.2.4 on 2021-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0018_approvedemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedemp',
            name='new',
        ),
        migrations.AddField(
            model_name='approvedemp',
            name='loginID',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='approvedemp',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
