# Generated by Django 3.2.4 on 2021-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0019_auto_20210708_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='Department',
            field=models.CharField(choices=[('Information Technology', 'IT'), ('Mobile App Development', 'MAD'), ('Java', 'Java'), ('Human Resources', 'HR')], default='HR', max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
