# Generated by Django 3.2.4 on 2021-07-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0021_alter_empdata_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='Phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empdata',
            name='empID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
