# Generated by Django 3.2.4 on 2021-07-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0022_auto_20210709_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdata',
            name='ip_address',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
