# Generated by Django 3.2.4 on 2021-07-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0023_empdata_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='ip_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
