# Generated by Django 3.2.4 on 2021-07-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0024_alter_empdata_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='empID',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
