# Generated by Django 3.2.4 on 2021-07-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0025_alter_empdata_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='Department',
            field=models.CharField(choices=[('Information Technology', 'IT'), ('Mobile App Development', 'MAD'), ('Java', 'Java'), ('Human Resources', 'HR'), ('Database Management', 'DBMS'), ('Admin', 'Admin')], default='HR', max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='OneDayAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceDate', models.DateField(auto_now_add=True, null=True)),
                ('attendaceStatus', models.CharField(choices=[('A', 'Absent'), ('P', 'Present')], max_length=120, null=True)),
                ('regEmployee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.approvedemp')),
            ],
        ),
    ]
