# Generated by Django 3.2.4 on 2021-07-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0026_auto_20210714_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedayattendance',
            name='login_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onedayattendance',
            name='logout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onedayattendance',
            name='attendaceStatus',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True),
        ),
    ]
