# Generated by Django 3.2.4 on 2021-07-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0027_auto_20210714_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onedayattendance',
            old_name='attendaceStatus',
            new_name='attendanceStatus',
        ),
    ]
