# Generated by Django 3.2.4 on 2021-07-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0028_rename_attendacestatus_onedayattendance_attendancestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedayattendance',
            name='attendanceDate',
            field=models.DateField(null=True),
        ),
    ]
