# Generated by Django 3.2.4 on 2021-07-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0029_alter_onedayattendance_attendancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedayattendance',
            name='regEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.approvedemp'),
        ),
    ]
