# Generated by Django 3.2.4 on 2021-07-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0031_alter_onedayattendance_regemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedayattendance',
            name='attendanceDate',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='onedayattendance',
            name='regEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.approvedemp'),
        ),
    ]
