# Generated by Django 3.2.4 on 2021-07-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0032_auto_20210714_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedayattendance',
            name='attendanceDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
