# Generated by Django 3.2.4 on 2021-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0033_alter_onedayattendance_attendancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedayattendance',
            name='active_Status',
            field=models.BooleanField(default=False),
        ),
    ]
