# Generated by Django 3.2.4 on 2021-07-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0034_onedayattendance_active_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.onedayattendance')),
            ],
        ),
    ]
