# Generated by Django 3.2.4 on 2021-07-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0037_auto_20210714_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkingDays',
            new_name='WorkingDay',
        ),
    ]
