# Generated by Django 3.2.4 on 2021-07-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0038_rename_workingdays_workingday'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], max_length=120, null=True)),
                ('active_Status', models.BooleanField(default=False)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.workingday')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.approvedemp')),
            ],
        ),
        migrations.RemoveField(
            model_name='oattendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='oattendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='onedayattendance',
            name='regEmployee',
        ),
        migrations.DeleteModel(
            name='MonthlyAttendance',
        ),
        migrations.DeleteModel(
            name='OAttendance',
        ),
        migrations.DeleteModel(
            name='OneDayAttendance',
        ),
    ]
