# Generated by Django 3.2.4 on 2021-07-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0039_auto_20210714_2207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceModel',
            new_name='AttendanceData',
        ),
    ]
