# Generated by Django 3.2.4 on 2021-07-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0040_rename_attendancemodel_attendancedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDonePerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=1000, null=True)),
                ('attendance_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.attendancedata')),
            ],
        ),
    ]
