# Generated by Django 3.2.4 on 2021-07-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0041_workdoneperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdoneperday',
            name='attendance_date',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.attendancedata'),
        ),
    ]
