# Generated by Django 3.2.4 on 2021-07-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0043_alter_workdoneperday_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdoneperday',
            old_name='details',
            new_name='task_assignment',
        ),
        migrations.AddField(
            model_name='workdoneperday',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.approvedemp'),
        ),
        migrations.AddField(
            model_name='workdoneperday',
            name='task_status',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
