# Generated by Django 3.2.4 on 2021-07-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0044_auto_20210726_1004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workdoneperday',
            table='Tasks',
        ),
    ]
