# Generated by Django 3.2.4 on 2021-07-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0045_alter_workdoneperday_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvedemp',
            options={'verbose_name_plural': 'Approved Employees'},
        ),
        migrations.AlterModelOptions(
            name='attendancedata',
            options={'verbose_name_plural': 'Attendance Data'},
        ),
        migrations.AlterModelOptions(
            name='empdata',
            options={'verbose_name': 'Employee Registration'},
        ),
        migrations.AlterModelOptions(
            name='workdoneperday',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterField(
            model_name='workdoneperday',
            name='task_assignment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workdoneperday',
            name='task_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
