# Generated by Django 3.2.4 on 2021-07-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0046_auto_20210726_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdoneperday',
            name='attendance_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpAccounts.workingday'),
        ),
    ]
