# Generated by Django 3.2.4 on 2021-07-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAccounts', '0048_workdoneperday_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdoneperday',
            name='task_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
